interface UserProfileInterface {
    id:             number;
    username:       string;
    avatar:         string;
    description:    string;
    website:        string;
    github:         string;
    twitter:        string;
    telegram:       string;
    home:           string;
    first_name:     string;
    last_name:      string;
    anime_name:     string;
    money:          number;
    verified:       boolean;
    date_joined:    Date;
    last_login:     Date;
    is_online:      boolean;
    is_active:      boolean;
    last_activity:  Date;
    xp:             number;
    css:            string;
    comments_count: number;
    reviews_count:  number;
    achievements:   [string];
    anime_lists:    [string];
    success:        boolean;
    referer:        null;
}
