services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - HOSTNAME=0.0.0.0
