services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: runner-full
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_SEARCH_API_URL: ${NEXT_PUBLIC_SEARCH_API_URL}
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_BASE_URL=https://api.aniua.top/
      - NEXT_PUBLIC_SEARCH_API_URL=https://anibackts.fly.dev/api/